---

- name: Deny everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

# - name: Set logging
#   community.general.ufw:
#     logging: 'on'

# http://www.debian-administration.org/articles/187
# limit for 6 or more connections in the last 30 seconds
- community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow port WireGuard(51820/udp)
  community.general.ufw:
    rule: allow
    port: 51820
    proto: udp

- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
